### ISSUE TITLE
As a player, I would like to save my game state and be able to load my game state for a better playing experience

### ISSUE THREAD

**Issue by cagdasgerede** [cagdasgerede/JavaFX-Tetris-Clone#5]
- Implement a save functionality
- The saving state should be kept in local storage persistently
- Provide an ability to load a saved game state
- Implement a menu to saving/loading
- There should be options to determine the saving location

**Comment by ahmedtahas** [comment]
I would like to be assigned on this issue, Ahmed Taha Sarı 121101016
